### ISSUE TITLE
flowChart for Python Code

### ISSUE THREAD

**Issue by laimaretto** [jernejp21/python-flowChart#14]
Hi! Any plans of being able to use this software to generate a flowChart of a Python code?

Cheers!

Lucas

**Comment by jernejp21** [comment]
Sorry for late reply. I think it should be working also on python code if you use reference comments. Because C doesn't have classes, classes are not implemented. How would you like classes to be shown? If you have any example, please paste the image.

**Comment by jernejp21** [comment]
Works if `-l python` is used.
