### ISSUE TITLE
Not getting any output files in destination directory

### ISSUE THREAD

**Issue by harshalgithub** [jernejp21/python-flowChart#16]
I am trying to generate flowChart of Python source code (script with multiple Functions defined) but I am not getting any output on the destination directory.

below command I used,

python "D:\flowchart.py" -s "D:\source_file.py" -l python -d "D:\testFLow"

output:      Press any key to continue . . .

Please let me know if anything, I am missing...

**Comment by jernejp21** [comment]
How did you input reference comments into "source_file.py"?
When reference comments aren't placed correctly, there isn't output. I haven't done any error handling yet. Will do this in the future.

**Comment by jernejp21** [comment]
Closed due to inactivity.
